# theme
# theme: "minimal-mistakes-jekyll"
# minimal_mistakes_skin    : "dark"

# Site Settings
title: The Archive
description: test is test or test
locale                   : "ko-KR"
lang                     : "ko-KR"
name                     : The Archive
url                      : "https://movingwoo.github.io"
repository               : movingwoo/movingwoo.github.io
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"

# Assets Settings
baseurl: ""  # the subpath of your site, e.g. /blog
assets:
  source: assets
  destination: assets

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown

include:
  - _pages

# Board 페이지 설정
defaults:
  - scope:
      path: ""
    values:
      layout: "single" 
      comments: true
  - scope:
      path: "404.html"
    values:
      permalink: /404.html
  - scope:
      path: "board.html"
    values:
      permalink: /board