# theme
# theme: "minimal-mistakes-jekyll"
# minimal_mistakes_skin    : "dark"

# Site Settings
title: 뭐라도 하겠지
description: 나도 사람인데 뭐라도 하겠지
locale                   : "ko-KR"
lang                     : "ko-KR"
name                     : 뭐라도 하겠지
url                      : "https://movingwoo.com"
repository               : movingwoo/movingwoo.github.io
logo                     : "/assets/images/common/favicon_180x180.png"

# Robots.txt 설정
sitemap:
  sitemap_url: https://movingwoo.com/sitemap.xml
  robots_url: https://movingwoo.com/robots.txt

# Assets Settings
baseurl: ""  # the subpath of your site, e.g. /blog
assets:
  source: assets
  destination: assets

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap

markdown: kramdown

include:
  - _pages

# Board 페이지 설정
defaults:
  - scope:
      path: ""
    values:
      layout: "single" 
      comments: false
  - scope:
      path: "404.html"
    values:
      permalink: /404.html
  - scope:
      path: "board.html"
    values:
      permalink: /board
